export type Category =
  | 'Flat'
  | 'Gable'
  | 'Dome'
  | 'Mansard'
  | 'Hip'

export interface Project {
  id: string
  category: Category
  style: string
  build: string
  label: string
  image: string
}

export const CATEGORIES: Category[] = [
  'Flat',
  'Gable',
  'Dome',
  'Mansard',
  'Hip',
]

export const projects: Project[] = [
  {
    id: '1',
    category: 'Hip',
    style: 'Roof-Over',
    build: 'Standard',
    label: 'Hip Pool Enclosure',
    image: '/projects/project-122978.jpg',
  },
  {
    id: '2',
    category: 'Hip',
    style: 'Roof-Over',
    build: 'Standard',
    label: 'Hip Pool Enclosure',
    image: '/projects/project-122980.jpg',
  },
  {
    id: '3',
    category: 'Dome',
    style: 'Free Standing',
    build: 'Full Dome',
    label: 'Dome Pool Enclosure',
    image: '/projects/project-122977.jpg',
  },
  {
    id: '5',
    category: 'Dome',
    style: 'Free Standing',
    build: 'Full Dome',
    label: 'Dome Pool Enclosure',
    image: '/projects/project-72552.jpg',
  },
  {
    id: '6',
    category: 'Gable',
    style: 'Free Standing',
    build: 'Full Structure',
    label: 'Gable Enclosure',
    image: '/projects/project-72553.jpg',
  },
  {
    id: '7',
    category: 'Gable',
    style: 'Free Standing',
    build: 'Full Structure',
    label: 'Gable Enclosure',
    image: '/projects/project-72554.jpg',
  },
  {
    id: '8',
    category: 'Hip',
    style: 'Roof-Over',
    build: 'Standard',
    label: 'Hip Pool Enclosure',
    image: '/projects/project-72555.jpg',
  },
  {
    id: '10',
    category: 'Flat',
    style: 'Attached',
    build: 'Standard',
    label: 'Flat Roof Enclosure',
    image: '/projects/project-72557.jpg',
  },
  {
    id: '11',
    category: 'Gable',
    style: 'Free Standing',
    build: 'Full Structure',
    label: 'Gable Enclosure',
    image: '/projects/project-72558.jpg',
  },
  {
    id: '12',
    category: 'Gable',
    style: 'Free Standing',
    build: 'Full Structure',
    label: 'Gable Enclosure',
    image: '/projects/project-72559.jpg',
  },
  {
    id: '13',
    category: 'Gable',
    style: 'Under Existing Gable',
    build: 'Tie-In',
    label: 'Gable Tie-In Enclosure',
    image: '/projects/project-72560.jpg',
  },
  {
    id: '14',
    category: 'Flat',
    style: 'Attached',
    build: 'Standard',
    label: 'Flat Roof Enclosure',
    image: '/projects/project-72561.jpg',
  },
  {
    id: '15',
    category: 'Flat',
    style: 'Attached',
    build: 'Standard',
    label: 'Flat Roof Enclosure',
    image: '/projects/project-72562.jpg',
  },
  {
    id: '16',
    category: 'Gable',
    style: 'Free Standing',
    build: 'Full Structure',
    label: 'Gable Enclosure',
    image: '/projects/project-72563.jpg',
  },
  {
    id: '17',
    category: 'Flat',
    style: 'Attached',
    build: 'Standard',
    label: 'Flat Roof Enclosure',
    image: '/projects/project-72564.jpg',
  },
  {
    id: '18',
    category: 'Mansard',
    style: 'Roof-Over',
    build: 'Standard',
    label: 'Mansard Pool Enclosure',
    image: '/projects/project-72565.jpg',
  },
  {
    id: '19',
    category: 'Flat',
    style: 'Attached',
    build: 'Standard',
    label: 'Flat Roof Enclosure',
    image: '/projects/project-72566.jpg',
  },
  {
    id: '20',
    category: 'Gable',
    style: 'Free Standing',
    build: 'Full Structure',
    label: 'Gable Enclosure',
    image: '/projects/project-72567.jpg',
  },
  {
    id: '21',
    category: 'Flat',
    style: 'Attached',
    build: 'Standard',
    label: 'Flat Roof Enclosure',
    image: '/projects/project-72568.jpg',
  },
  {
    id: '22',
    category: 'Gable',
    style: 'Free Standing',
    build: 'Full Structure',
    label: 'Gable Enclosure',
    image: '/projects/project-72569.jpg',
  },
  {
    id: '23',
    category: 'Flat',
    style: 'Attached',
    build: 'Standard',
    label: 'Flat Roof Enclosure',
    image: '/projects/project-72570.jpg',
  },
  {
    id: '24',
    category: 'Gable',
    style: 'Free Standing',
    build: 'Full Structure',
    label: 'Gable Enclosure',
    image: '/projects/project-72571.jpg',
  },
  {
    id: '25',
    category: 'Gable',
    style: 'Free Standing',
    build: 'Full Structure',
    label: 'Gable Enclosure',
    image: '/projects/project-72572.jpg',
  },
  {
    id: '26',
    category: 'Flat',
    style: 'Attached',
    build: 'Standard',
    label: 'Flat Roof Enclosure',
    image: '/projects/project-72573.jpg',
  },
  {
    id: '27',
    category: 'Gable',
    style: 'Free Standing',
    build: 'Full Structure',
    label: 'Gable Enclosure',
    image: '/projects/project-72574.jpg',
  },
  {
    id: '28',
    category: 'Gable',
    style: 'Free Standing',
    build: 'Full Structure',
    label: 'Gable Enclosure',
    image: '/projects/project-72575.jpg',
  },
]

export function getProjectsByCategory(category: Category): Project[] {
  return projects.filter((p) => p.category === category)
}

// Static fallback gallery — at least 10 photos per category.
// Used when CompanyCam has no live projects for a given category.
export const STATIC_GALLERY_BY_CATEGORY: Record<string, string[]> = {
  Flat: [
    '/projects/project-72557.jpg',
    '/projects/project-72561.jpg',
    '/projects/project-72562.jpg',
    '/projects/project-72564.jpg',
    '/projects/project-72566.jpg',
    '/projects/project-72568.jpg',
    '/projects/project-72570.jpg',
    '/projects/project-72573.jpg',
    '/projects/project-72553.jpg',
    '/projects/project-72554.jpg',
  ],
  Gable: [
    '/projects/project-72553.jpg',
    '/projects/project-72554.jpg',
    '/projects/project-72558.jpg',
    '/projects/project-72559.jpg',
    '/projects/project-72563.jpg',
    '/projects/project-72567.jpg',
    '/projects/project-72569.jpg',
    '/projects/project-72571.jpg',
    '/projects/project-72572.jpg',
    '/projects/project-72574.jpg',
    '/projects/project-72575.jpg',
  ],
  Dome: [
    '/projects/project-122977.jpg',
    '/projects/project-72552.jpg',
    '/projects/project-72558.jpg',
    '/projects/project-72563.jpg',
    '/projects/project-72569.jpg',
    '/projects/project-72571.jpg',
    '/projects/project-72572.jpg',
    '/projects/project-72574.jpg',
    '/projects/project-72575.jpg',
    '/projects/project-72553.jpg',
  ],
  Mansard: [
    '/projects/project-72565.jpg',
    '/projects/project-122978.jpg',
    '/projects/project-122980.jpg',
    '/projects/project-72555.jpg',
    '/projects/project-72558.jpg',
    '/projects/project-72563.jpg',
    '/projects/project-72571.jpg',
    '/projects/project-72572.jpg',
    '/projects/project-72574.jpg',
    '/projects/project-72575.jpg',
  ],
  Hip: [
    '/projects/project-122978.jpg',
    '/projects/project-122980.jpg',
    '/projects/project-72555.jpg',
    '/projects/project-72565.jpg',
    '/projects/project-72558.jpg',
    '/projects/project-72563.jpg',
    '/projects/project-72571.jpg',
    '/projects/project-72572.jpg',
    '/projects/project-72574.jpg',
    '/projects/project-72575.jpg',
  ],
  'Elite Room': [
    '/projects/project-72557.jpg',
    '/projects/project-72561.jpg',
    '/projects/project-72562.jpg',
    '/projects/project-72564.jpg',
    '/projects/project-72566.jpg',
    '/projects/project-72568.jpg',
    '/projects/project-72570.jpg',
    '/projects/project-72573.jpg',
    '/projects/project-72553.jpg',
    '/projects/project-72554.jpg',
  ],
  'Under Existing': [
    '/projects/project-72560.jpg',
    '/projects/project-72553.jpg',
    '/projects/project-72554.jpg',
    '/projects/project-72558.jpg',
    '/projects/project-72559.jpg',
    '/projects/project-72563.jpg',
    '/projects/project-72567.jpg',
    '/projects/project-72569.jpg',
    '/projects/project-72571.jpg',
    '/projects/project-72572.jpg',
  ],
}
